title:              Andy's Note
email:              mitacfae995@gmail.com
description:        To avoid missing out, write it down so you won't forget it.
author:             Andy
baseurl:            "/"
url:                "https://mitacfae.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    mitacfae
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:  andy-yang-0209b2b6

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
