title:              Andy's Note
email:              mitacfae995@gmail.com
description:        To avoid missing out, write it down so you won't forget it.
author:             Andy
baseurl:            ""
url:                "https://mitacfae.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    mitacfae
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:  andy-yang-0209b2b6

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-QKTN538X44 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap          ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
tag_page_layout: tag_page   ## add this function at 2026/06/14
tag_page_dir: tag           ## add this function at 2026/06/14

  
# 新增或移除 categories 項目即可更新右側 sidebar

# 尋找類似以下的區塊並加入 Categories
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Posts
    url: /posts
  - title: Categories
    url: /categories/
  - title: Contact
    url: /contact
